events {}

http {
  server {
    listen 80;
    server_name statsy.in www.statsy.in 34.131.73.27;

    # Handle _next/static files directly
    location /_next/static/ {
      proxy_pass http://frontend:3000/_next/static/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }

    # Frontend
    location / {
      proxy_pass http://frontend:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_cache_bypass $http_upgrade;
    }

    # Backend API
    location /api {
      proxy_pass http://server:4000;
      
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      
      proxy_pass_request_headers on;
      proxy_set_header Cookie $http_cookie;
    }
  }
}
